import numpy as np

def extractThermalProperties(file_name):
    """
    This function extracts the thermal properties from the thermal_properties.yaml
    generated by phonopy software.
    You only have to provide the name of the file and function will return a numpy
    array with five coloumns:
      Temperature | Free Energy | Entropy | Heat Capacity | Energy
      ------------|-------------|---------|---------------|---------
    """
    file = open(file_name, "r")

    startGettingData = False
    freeEnergy = False

    data_array = np.zeros((101,5))
    i_index = 0
    j_index = 0


    for x in file:
        actual_string = x
        if 'thermal_properties:' in actual_string:
            startGettingData = True
    
        if startGettingData == True:
            if 'temperature:' in actual_string:
                data_array[i_index,j_index] = float(actual_string.split()[2])
            
                j_index = j_index + 1
            
            if 'free_energy:' in actual_string:
                data_array[i_index,j_index] = float(actual_string.split()[1])
            
                j_index = j_index + 1
            
            if 'entropy:' in actual_string:
                data_array[i_index,j_index] = float(actual_string.split()[1])
            
                j_index = j_index + 1
            
            if 'heat_capacity:' in actual_string:
                data_array[i_index,j_index] = float(actual_string.split()[1])
            
                freeEnergy = True 
                j_index = j_index + 1
            
            if 'energy:' in actual_string and freeEnergy == True:
                data_array[i_index,j_index] = float(actual_string.split()[1])
            
                freeEnergy = False
                j_index = 0
                i_index = i_index + 1

    
    file.close()
    return data_array